#!/bin/bash

# This script is run when the application starts
# Its purpose is to print out the current wallpaper as an absolute path, or file URI (e.g. file://a/b.jpg)
# You need to edit this if you use something other than Gnome 3 or Unity for a desktop environment

# Gnome 3, Unity:
gsettings get org.gnome.desktop.background picture-uri

# XFCE
# TODO

# Other examples - TODO
