#!/usr/bin/env bash
# This regenerates the pot file into po/variety.pot
# This file must then be uploaded to https://translations.launchpad.net/variety/trunk/+translations-upload

cd po || cd ../po

TARGET="variety.pot"
xgettext -k_ -kN_ -L Python -o "$TARGET" \
    ../variety/*.py \
    ../variety/**/*.py \
    ../variety_lib/*.py \
    ../jumble/*.py
xgettext -k_ -kN_ -L Glade -j -o "$TARGET" \
    ../data/ui/*.ui
